export const ALARMS_ = [
  {  
    "alarm_description":"temp_description",
    "alarm_code":"TMP101",
    "alarm_enable":true,
    "alarm_solution":"temp_solution",
    "alarm_type":"tech",
    "alarm_name":"temp_alert",
    "alarm_state":true,
    "alarm_category":"super_alert",
    "alarm_date":"1970-01-01T00:00:00"
  },
  {  
     "alarm_description":"press_h2o_description",
     "alarm_code":"PRS101",
     "alarm_enable":true,
     "alarm_solution":"press_h2o_solution",
     "alarm_type":"tech",
     "alarm_name":"press_h2o",
     "alarm_state":true,
     "alarm_category":"super_alert",
     "alarm_date":"1970-01-01T00:00:00"
  },
  {
    "alarm_description": "press_co2_description",
    "alarm_code": "PRS102",
    "alarm_enable": true,
    "alarm_solution": "press_co2_solution",
    "alarm_type": "tech",
    "alarm_name": "press_co2",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "timeout_plain_description",
    "alarm_code": "ENG103",
    "alarm_enable": true,
    "alarm_solution": "timeout_plain_solution",
    "alarm_type": "tech",
    "alarm_name": "timeout_plain",
    "alarm_state": true,
    "alarm_category": "alert",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "timeout_pump_description",
    "alarm_code": "ENG104",
    "alarm_enable": true,
    "alarm_solution": "timeout_pump_solution",
    "alarm_type": "tech",
    "alarm_name": "timeout_pump",
    "alarm_state": true,
    "alarm_category": "alert",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "timeout_compressor_description",
    "alarm_code": "ENG102",
    "alarm_enable": true,
    "alarm_solution": "timeout_compressor_solution",
    "alarm_type": "tech",
    "alarm_name": "timeout_compressor",
    "alarm_state": true,
    "alarm_category": "alert",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "level_switch_timeout_description",
    "alarm_code": "LVL104",
    "alarm_enable": true,
    "alarm_solution": "level_switch_timeout_solution",
    "alarm_type": "tech",
    "alarm_name": "level_switch_timeout",
    "alarm_state": true,
    "alarm_category": "alert",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "network_description",
    "alarm_code": "TRM101",
    "alarm_enable": true,
    "alarm_solution": "network_solution",
    "alarm_type": "tech",
    "alarm_name": "network",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "2019-08-08T10:41:26"
  },
  {
    "alarm_description": "powerboard_description",
    "alarm_code": "ELT102",
    "alarm_enable": true,
    "alarm_solution": "powerboard_solution",
    "alarm_type": "tech",
    "alarm_name": "powerboard",
    "alarm_state": true,
    "alarm_category": "super_alert",
    "alarm_date": "2019-08-07T12:55:41"
  },
  {
    "alarm_description": "flux_water_description",
    "alarm_code": "FLW101",
    "alarm_enable": true,
    "alarm_solution": "flux_water_solution",
    "alarm_type": "tech",
    "alarm_name": "flux_water",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "flux_soda_description",
    "alarm_code": "FLW102",
    "alarm_enable": true,
    "alarm_solution": "flux_soda_solution",
    "alarm_type": "tech",
    "alarm_name": "flux_soda",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "ada_panel_description",
    "alarm_code": "ELT103",
    "alarm_enable": true,
    "alarm_solution": "ada_panel_solution",
    "alarm_type": "tech",
    "alarm_name": "ada_panel",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "2019-07-09T12:25:13"
  },
  {
    "alarm_description": "ps_als_description",
    "alarm_code": "ELT104",
    "alarm_enable": true,
    "alarm_solution": "ps_als_solution",
    "alarm_type": "tech",
    "alarm_name": "ps_als",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "webcam_description",
    "alarm_code": "ELT105",
    "alarm_enable": true,
    "alarm_solution": "webcam_solution",
    "alarm_type": "tech",
    "alarm_name": "webcam",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "touchscreen_description",
    "alarm_code": "ELT106",
    "alarm_enable": true,
    "alarm_solution": "touchscreen_solution",
    "alarm_type": "tech",
    "alarm_name": "touchscreen",
    "alarm_state": true,
    "alarm_category": "super_alert",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "modem_description",
    "alarm_code": "ELT107",
    "alarm_enable": true,
    "alarm_solution": "modem_solution",
    "alarm_type": "tech",
    "alarm_name": "modem",
    "alarm_state": true,
    "alarm_category": "alert",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {
    "alarm_description": "payment_description",
    "alarm_code": "ELT108",
    "alarm_enable": true,
    "alarm_solution": "payment_solution",
    "alarm_type": "tech",
    "alarm_name": "payment",
    "alarm_state": true,
    "alarm_category": "alert",
    "alarm_date": "2019-07-15T11:38:54"
  },
  {
    "alarm_description": "mqtt_description",
    "alarm_code": "TRM102",
    "alarm_enable": true,
    "alarm_solution": "mqtt_solution",
    "alarm_type": "tech",
    "alarm_name": "mqtt",
    "alarm_state": true,
    "alarm_category": "warning",
    "alarm_date": "2019-08-08T14:35:53"
  },
  {
    "alarm_description": "gicar_description",
    "alarm_code": "ELT101",
    "alarm_enable": true,
    "alarm_solution": "gicar_solution",
    "alarm_type": "tech",
    "alarm_name": "gicar_connection",
    "alarm_state": true,
    "alarm_category": "alert",
    "alarm_date": "1970-01-01T00:00:00"
  },
  {  
    "alarm_description":"flux1_description",
    "alarm_code":"FLW110",
    "alarm_enable":true,
    "alarm_solution":"flux1_solution",
    "alarm_type":"tech",
    "alarm_name":"flux1",
    "alarm_state":true,
    "alarm_category":"alert",
    "alarm_date":"1970-01-01T00:00:00"
 },
 {  
    "alarm_description":"flux2_description",
    "alarm_code":"FLW111",
    "alarm_enable":true,
    "alarm_solution":"flux2_solution",
    "alarm_type":"tech",
    "alarm_name":"flux2",
    "alarm_state":true,
    "alarm_category":"alert",
    "alarm_date":"1970-01-01T00:00:00"
 },
 {  
    "alarm_description":"flux3_description",
    "alarm_code":"FLW112",
    "alarm_enable":true,
    "alarm_solution":"flux3_solution",
    "alarm_type":"tech",
    "alarm_name":"flux3",
    "alarm_state":true,
    "alarm_category":"alert",
    "alarm_date":"1970-01-01T00:00:00"
 },
 {  
    "alarm_description":"flux4_description",
    "alarm_code":"FLW113",
    "alarm_enable":true,
    "alarm_solution":"flux4_solution",
    "alarm_type":"tech",
    "alarm_name":"flux4",
    "alarm_state":true,
    "alarm_category":"alert",
    "alarm_date":"1970-01-01T00:00:00"
 },
 {  
    "alarm_description":"flux5_description",
    "alarm_code":"FLW114",
    "alarm_enable":true,
    "alarm_solution":"flux5_solution",
    "alarm_type":"tech",
    "alarm_name":"flux5",
    "alarm_state":true,
    "alarm_category":"alert",
    "alarm_date":"1970-01-01T00:00:00"
 },
 {  
    "alarm_description":"flux6_description",
    "alarm_code":"FLW115",
    "alarm_enable":true,
    "alarm_solution":"flux6_solution",
    "alarm_type":"tech",
    "alarm_name":"flux6",
    "alarm_state":true,
    "alarm_category":"alert",
    "alarm_date":"1970-01-01T00:00:00"
 }
];